on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - devel
      - pre-release

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 3.6

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Install dependencies
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          BRANCH_OR_TAG="${GITHUB_REF##*/}"
          Rscript - <<EOF
          pkgdown::deploy_to_branch(
            new_process = FALSE,
            subdir = "${BRANCH_OR_TAG}",
            clean = TRUE
          )
          EOF

  multi-version-docs:
    name: Multi-version docs 📑
    needs: pkgdown
    runs-on: ubuntu-20.04
    if: >
      github.event_name == 'push'
        && !contains(github.event.commits[0].message, '[skip docs]')
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
          ref: "gh-pages"

      - name: Create and publish docs ↗️
        uses: insightsengineering/r-pkgdown-multiversion@v2
        with:
          path: ${{ github.event.repository.name }}
          default-landing-page: "main"
